spring:
  application:
    name: message-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          transport:
            protocol: smtp
          writetimeout: 5000